#!/usr/bin/env python3
"""One-off generator: reads Backend/Api/AtmInventory.db (SQLite) and the MySQL column types
exported from AtmInventory's information_schema (mysql_columns.tsv), and writes a plain .sql
file of INSERT statements that loads the same data into a MySQL database whose schema was
already created (e.g. via InitialCreate.sql). Not part of the app; run manually when a fresh
data-only migration script is needed. Requires no MySQL driver — column types come from the
TSV dump, not a live connection.
"""
import sqlite3
import sys
from pathlib import Path

SQLITE_PATH = Path(__file__).resolve().parents[1] / "AtmInventory.db"
COLUMNS_TSV = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("/tmp/mysql_columns.tsv")
OUT_PATH = Path(__file__).resolve().parents[1] / "DataMigration_SqliteToMySql.sql"
BATCH_SIZE = 200

def load_column_types(tsv_path):
    tables = {}  # table -> list of (column, data_type, is_nullable)
    with open(tsv_path, encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line:
                continue
            table, col, data_type, is_nullable, _column_type = line.split("\t")
            tables.setdefault(table, []).append((col, data_type, is_nullable == "YES"))
    return tables

def escape_string(s: str) -> str:
    return (
        s.replace("\\", "\\\\")
         .replace("'", "\\'")
         .replace("\r", "\\r")
         .replace("\n", "\\n")
         .replace("\x00", "")
    )

def format_value(value, data_type: str):
    if value is None:
        return "NULL"
    if data_type in ("int", "bigint", "smallint", "tinyint", "decimal", "double", "float"):
        if data_type == "tinyint":
            # bool columns: SQLite stores 0/1 already; anything truthy -> 1
            return "1" if value not in (0, "0", False, None) else "0"
        return str(value)
    if data_type in ("datetime", "date", "timestamp"):
        s = str(value).strip()
        if s == "":
            return "NULL"
        # SQLite ISO text ('YYYY-MM-DD HH:MM:SS[.ffffff]') is already MySQL-compatible.
        s = s.replace("T", " ")
        return f"'{escape_string(s)}'"
    # varchar / longtext / text / char / json fallback
    return f"'{escape_string(str(value))}'"

# Known source-data issues that only collide once landed in MySQL (whose default collation is
# case-insensitive, unlike SQLite's default). Fix applied only to the generated SQL, not to the
# SQLite source, so re-running this generator against the live dev DB stays reproducible.
# Parts.Id 15 ("An.J V030006") and 817 ("AN.J V030006") are genuine duplicate rows (same part,
# re-entered) that collide under MySQL's unique index on PartNo — Id 15 gets a "-DUP" suffix so
# both rows migrate; dedupe for real is a separate follow-up, not something to silently resolve here.
def apply_known_fixups(table, row, col_names):
    if table == "Parts":
        row = list(row)
        id_idx = col_names.index("Id")
        if row[id_idx] == 15:
            partno_idx = col_names.index("PartNo")
            row[partno_idx] = f"{row[partno_idx]}-DUP"
        row = tuple(row)
    return row

def main():
    if not SQLITE_PATH.exists():
        sys.exit(f"SQLite source not found: {SQLITE_PATH}")
    if not COLUMNS_TSV.exists():
        sys.exit(f"MySQL column-type TSV not found: {COLUMNS_TSV}")

    tables = load_column_types(COLUMNS_TSV)

    conn = sqlite3.connect(str(SQLITE_PATH))
    conn.row_factory = sqlite3.Row
    cur = conn.cursor()
    cur.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name != '__EFMigrationsHistory'")
    sqlite_tables = {r[0] for r in cur.fetchall()}

    lines = []
    lines.append("-- Data-only migration: Backend/Api/AtmInventory.db (SQLite) -> MySQL AtmInventory")
    lines.append("-- Generated by Tools/generate_sqlite_to_mysql_data_sql.py — run against an already-created schema")
    lines.append("-- (e.g. after InitialCreate.sql). Safe to re-run only against an EMPTY database: no ON DUPLICATE")
    lines.append("-- KEY UPDATE / upsert logic, plain INSERTs.")
    lines.append("SET FOREIGN_KEY_CHECKS=0;")
    lines.append("SET NAMES utf8mb4;")
    lines.append("")

    total_rows = 0
    for table, columns in tables.items():
        if table not in sqlite_tables:
            continue
        col_names = [c[0] for c in columns]
        col_list_sql = ", ".join(f"`{c}`" for c in col_names)

        quoted_cols = ", ".join(f'"{c}"' for c in col_names)
        cur.execute(f'SELECT {quoted_cols} FROM "{table}"')
        rows = cur.fetchall()
        if not rows:
            continue

        lines.append(f"-- {table} ({len(rows)} rows)")
        for i in range(0, len(rows), BATCH_SIZE):
            batch = rows[i:i + BATCH_SIZE]
            value_tuples = []
            for row in batch:
                row = apply_known_fixups(table, row, col_names)
                vals = [format_value(row[idx], columns[idx][1]) for idx in range(len(columns))]
                value_tuples.append(f"({', '.join(vals)})")
            lines.append(f"INSERT INTO `{table}` ({col_list_sql}) VALUES")
            lines.append(",\n".join(value_tuples) + ";")
        lines.append("")
        total_rows += len(rows)

    lines.append("SET FOREIGN_KEY_CHECKS=1;")

    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT_PATH} — {total_rows} rows across {len(tables)} tables")

if __name__ == "__main__":
    main()
